### ISSUE TITLE
Extracting just the typescript types from the repo

### ISSUE THREAD

**Issue by percimar** [iquirino/google-wallet#41]
Hiya, great work on the repo! I'm working on integrating google wallet, and having the loyaltyObject and loyaltyClass typed would be extremely useful, however I don't want to add a new runtime dependency. Would you be opposed to me forking the repo to create one with just types? Alternatively, would you mind if the types were contributed to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)?

**Comment by iquirino** [comment]
What you don't like from the implementation?
If you just want typings, I intend that you will implement the API calls yourself.
We can work together and make it happy to all people.
;)
